In [12]:
from pprint import pprint
import torch

t1 = torch.tensor(list(range(3*4*5)), dtype=torch.float32).view(3,4,5)
pprint(t1)
print(t1.shape)
print("---------------")
pprint(t1.transpose(0,1))
print(t1.transpose(0,1).shape)

tensor([[[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]],

        [[20., 21., 22., 23., 24.],
         [25., 26., 27., 28., 29.],
         [30., 31., 32., 33., 34.],
         [35., 36., 37., 38., 39.]],

        [[40., 41., 42., 43., 44.],
         [45., 46., 47., 48., 49.],
         [50., 51., 52., 53., 54.],
         [55., 56., 57., 58., 59.]]])
torch.Size([3, 4, 5])
---------------
tensor([[[ 0.,  1.,  2.,  3.,  4.],
         [20., 21., 22., 23., 24.],
         [40., 41., 42., 43., 44.]],

        [[ 5.,  6.,  7.,  8.,  9.],
         [25., 26., 27., 28., 29.],
         [45., 46., 47., 48., 49.]],

        [[10., 11., 12., 13., 14.],
         [30., 31., 32., 33., 34.],
         [50., 51., 52., 53., 54.]],

        [[15., 16., 17., 18., 19.],
         [35., 36., 37., 38., 39.],
         [55., 56., 57., 58., 59.]]])
torch.Size([4, 3, 5])


In [1]:

import torch
from argparse import ArgumentParser
from pprint import pprint
from tqdm import tqdm
import time

from arguments import ModelParams, PipelineParams, OptimizationParams

# test GaussianModel
from scene.gaussian_model import GaussianModel
from scene import Scene

parser = ArgumentParser(description="Training script parameters")
lp = ModelParams(parser)
op = OptimizationParams(parser)
pp = PipelineParams(parser)
parser.add_argument('--ip', type=str, default="127.0.0.1")
parser.add_argument('--port', type=int, default=6009)
parser.add_argument('--debug_from', type=int, default=-1)
parser.add_argument('--detect_anomaly', action='store_true', default=False)
parser.add_argument("--test_iterations", nargs="+", type=int, default=[7_000, 30_000])
parser.add_argument("--save_iterations", nargs="+", type=int, default=[7_000, 30_000])
parser.add_argument("--quiet", action="store_true")
parser.add_argument("--checkpoint_iterations", nargs="+", type=int, default=[])
parser.add_argument("--start_checkpoint", type=str, default = None)
args = parser.parse_args(args=[
    "--source_path", "/home/youngdong/dataset/tandt/train"
])

model_args = lp.extract(args)

gaussian_model = GaussianModel(sh_degree=100)
scene = Scene(model_args, gaussian_model)
gaussian_model.training_setup(op)

/home/hjp/.conda/envs/gs/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Reading camera 301/301
Loading Training Cameras
Loading Test Cameras
Number of points at initialisation :  182686


In [2]:
from utils.system_utils import searchForMaxIteration
from scene.dataset_readers import sceneLoadTypeCallbacks
from scene.gaussian_model import GaussianModel
from arguments import ModelParams
from utils.camera_utils import cameraList_from_camInfos, camera_to_JSON

scene_info = sceneLoadTypeCallbacks["Colmap"](
    model_args.source_path,
    model_args.images,
    model_args.eval
)

Reading camera 301/301


In [11]:
gaussian_model._scaling

Parameter containing:
tensor([[-5.1215, -5.1215, -5.1215],
        [-4.7858, -4.7858, -4.7858],
        [-4.8477, -4.8477, -4.8477],
        ...,
        [-4.2819, -4.2819, -4.2819],
        [-4.2442, -4.2442, -4.2442],
        [-4.0797, -4.0797, -4.0797]], device='cuda:0', requires_grad=True)